spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/band_website
spring.datasource.username=tatanakovalenko
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true